# Generated by Django 5.2 on 2025-04-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='potal_code',
            new_name='pin_code',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='house_street',
            new_name='town_city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city_village',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.AddField(
            model_name='address',
            name='Landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='area_street_sector_village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_default_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='local_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
